source 'https://rubygems.org'

gem 'linkeddata', '>= 3.1.1'
gem 'json-ld-preloaded'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.11.0'
gem 'equivalent-xml', '>= 0.6.0'

group :debug do
  gem 'byebug'
end
